name: Trigger auto deployment for moracorpjuiceshop

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/moracorpjuiceshop-AutoDeployTrigger-22e92728-4562-467d-813f-06185ddf9be4.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: kramericaindustries.azurecr.io
          username: ${{ secrets.MORACORPJUICESHOP_REGISTRY_USERNAME }}
          password: ${{ secrets.MORACORPJUICESHOP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kramericaindustries.azurecr.io/moracorpjuiceshop:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MORACORPJUICESHOP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n moracorpjuiceshop -g app-sec-testing-rg --server kramericaindustries.azurecr.io --username  ${{ secrets.MORACORPJUICESHOP_REGISTRY_USERNAME }} --password ${{ secrets.MORACORPJUICESHOP_REGISTRY_PASSWORD }}
            az containerapp update -n moracorpjuiceshop -g app-sec-testing-rg --image kramericaindustries.azurecr.io/moracorpjuiceshop:${{ github.sha }}
